version: "3.8"

services:
  backend:
    container_name: dcs-server
    image: ${DOCKERHUB_USERNAME}/devnogi-community-server:latest
    ports:
      - "8093:8093"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m
      - SPRING_PROFILES_ACTIVE=prod

      # application.yml 변수 매핑
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_SCHEMA=${DB_SCHEMA}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - TZ=Asia/Seoul
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - my-network
    restart: always

  redis:
    image: redis:7-alpine
    container_name: dcs-redis
    restart: unless-stopped
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: dcs-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_SCHEMA}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      LANG: C.UTF_8
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-time-zone=+09:00
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
