package until.the.eternity.dcs.infrastructure;

import until.the.eternity.dcs.domain.comment.entity.CommentLike;
import until.the.eternity.dcs.domain.comment.entity.CommentLikeRepository;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

public class FakeCommentLikeRepository implements CommentLikeRepository {
	private final Map<Long, CommentLike> db = new ConcurrentHashMap<>();
	private final AtomicLong autoGeneratedId = new AtomicLong(1);

	@Override
	public CommentLike findByCommentIdAndUserId(Long commentId, Long userId) {
		for (CommentLike commentLike : db.values()) {
			if (commentLike.getCommentId().equals(commentId) && commentLike.getUserId().equals(userId)) {
				return commentLike;
			}
		}
		return null;
	}

	@Override
	public CommentLike save(CommentLike commentLike) {
		CommentLike result = CommentLike.builder()
			.id(autoGeneratedId.getAndIncrement())
			.commentId(commentLike.getCommentId())
			.userId(commentLike.getUserId())
			.createdAt(LocalDateTime.now())
			.build();

		db.put(result.getId(), result);
		return result;
	}

	@Override
	public void deleteByCommentId(Long commentId) {
		db.values().forEach(commentLike -> {
			if (commentLike.getCommentId().equals(commentId)) {
				db.remove(commentLike.getId());
			}
		});
	}

	@Override
	public Set<Long> findIdsByUserIdAndCommentIdIn(Long userId, List<Long> commentIds) {
		Set<Long> result = new HashSet<>();

		db.values().forEach(commentLike -> {
			if (commentLike.getUserId().equals(userId) && commentIds.contains(commentLike.getId())) {
				result.add(commentLike.getId());
			}
		});

		return result;
	}

	public void clearDbForTest() {
		db.clear();
		autoGeneratedId.set(1);
	}
}
