package until.the.eternity.dcs.infrastructure;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import until.the.eternity.dcs.domain.comment.entity.Comment;
import until.the.eternity.dcs.domain.comment.entity.CommentRepository;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeCommentRepository implements CommentRepository {
	private final Map<Long, Comment> db = new ConcurrentHashMap<>();
	private final AtomicLong autoGeneratedId = new AtomicLong(1);

	@Override
	public Comment save(Comment comment) {
		Comment result = Comment.builder()
			.id(autoGeneratedId.getAndIncrement())
			.post(comment.getPost())
			.userId(comment.getUserId())
			.parentComment(comment.getParentComment())
			.childComments(new ArrayList<>())
			.content(comment.getContent())
			.likeCount(0)
			.isBlocked(false)
			.build();

		result.setCreatedAt(LocalDateTime.now());
		result.setUpdatedAt(LocalDateTime.now());

		db.put(result.getId(), result);
		return result;
	}

	@Override
	public Optional<Comment> findById(Long id) {
		Comment comment = db.get(id);
		if (comment == null || comment.getIsDeleted()) {
			return Optional.empty();
		}
		return Optional.of(comment);
	}

	@Override
	public Page<Comment> findByPost(Long postId, Pageable pageable) {
		List<Comment> filtered = db.values().stream()
			.filter(c -> c.getPost().getId().equals(postId))
			.sorted(Comparator.comparing(Comment::getCreatedAt))
			.collect(Collectors.toList());

		int pageSize = pageable.getPageSize();
		int currentPage = pageable.getPageNumber();
		int start = currentPage * pageSize;

		List<Comment> pageContent;
		if (start >= filtered.size()) {
			pageContent = Collections.emptyList();
		} else {
			int toIndex = Math.min(start + pageSize, filtered.size());
			pageContent = filtered.subList(start, toIndex);
		}

		return new PageImpl<>(pageContent, pageable, filtered.size());
	}

	public void clearDbForTest() {
		db.clear();
		autoGeneratedId.set(1);
	}
}
