package until.the.eternity.dcs.infrastructure;

import until.the.eternity.dcs.domain.board.entity.Board;
import until.the.eternity.dcs.domain.board.entity.BoardRepository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

public class FakeBoardRepository implements BoardRepository {
	private final Map<Long, Board> db = new ConcurrentHashMap<>();
	private final AtomicLong autoGeneratedId = new AtomicLong(1);

	@Override
	public Board save(Board board) {
		Board result = Board.builder()
			.id(autoGeneratedId.getAndIncrement())
			.name(board.getName())
			.description(board.getDescription())
			.topCategory(board.getTopCategory())
			.subCategory(board.getSubCategory())
			.createdBy(board.getCreatedBy())
			.build();

		result.setCreatedAt(LocalDateTime.now());
		result.setUpdatedAt(LocalDateTime.now());

		db.put(result.getId(), result);
		return result;
	}

	@Override
	public List<Board> findAll() {
		return db.values().stream().sorted((o1, o2) -> {
			if (o1.getTopCategory().equals(o2.getTopCategory())) {
				if (o1.getSubCategory().equals(o2.getSubCategory())) {
					return o1.getCreatedAt().compareTo(o2.getCreatedAt());
				}
				return o1.getSubCategory().compareTo(o2.getSubCategory());
			}
			return o1.getTopCategory().compareTo(o2.getTopCategory());
		}).toList();
	}

	@Override
	public Optional<Board> findById(Long id) {
		Board board = db.get(id);
		System.out.println(board.getIsDeleted());
		if (board.getIsDeleted()){
			return Optional.empty();
		}
		return Optional.of(board);
	}

	@Override
	public void deleteById(Long id) {
		db.remove(id);
	}

	public void clearDbForTest() {
		db.clear();
		autoGeneratedId.set(1);
	}
}
