name: deploy-with-docker.yml


on:
  push:
    branches:
      - chore/generate-ci/cd-pipeline # 현재 작업 중인 브랜치명
#on:
#  workflow_run:
#    workflows: ["CI Pipeline (pull-request-test, Build & Push on Merge).yml"]
#    types:
#      - completed
#    branches:
#      - dev
#      - chore/generate-ci/cd-pipeline # 테스트용

  workflow_dispatch:

jobs:
  deploy-to-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    #environment: prod

    steps:
      - name: SSH connect to server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker stop dcs-server || true
            docker rm dcs-server || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dcs-server:dev
            docker compose up -d